apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark-optimization.jupyterlab" . }}
  labels:
  {{- include "spark-optimization.commonLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "spark-optimization.jupyterSelectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
    {{- include "spark-optimization.jupyterSelectorLabels" . | indent 8 }}
    spec:
      hostname: spark-master
      containers:
        - name: {{ include "spark-optimization.jupyterlab" . }}
          image: "{{ .Values.image.jupyterLab.repository }}:{{ .Values.image.jupyterLab.tag }}"
          imagePullPolicy: {{ .Values.image.jupyterLab.pullPolicy }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          stdin: true
          tty: true
          ports:
            - containerPort: {{ .Values.services.jupyterLab.targetPort }}
            - containerPort: {{ .Values.services.jupyterLab.sparkUiTargetPort }}
            - containerPort: {{ .Values.services.jupyterLab.sparkUiTargetPort2 }}
          volumeMounts:
      {{- include "spark-client.pod-volumeMounts-shared" . | nindent 10 }}
      volumes:
  {{- include "spark-optimization.pod-volumes-share-pvc" . | nindent 6 }}