apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-optimization.name" . }}-jupyterlab-ui
  labels:
  {{- include "spark-optimization.commonLabels" . | indent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.services.jupyterLab.type }}
  selector:
  {{- include "spark-optimization.jupyterSelectorLabels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.jupyterLab.port }}
      targetPort: {{ .Values.services.jupyterLab.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-optimization.name" . }}-jupyterlab-spark-ui
  labels:
  {{- include "spark-optimization.commonLabels" . | indent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.services.jupyterLab.type }}
  selector:
  {{- include "spark-optimization.jupyterSelectorLabels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.jupyterLab.sparkUiPort }}
      targetPort: {{ .Values.services.jupyterLab.sparkUiTargetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-optimization.name" . }}-jupyterlab-spark-ui-2
  labels:
  {{- include "spark-optimization.commonLabels" . | indent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.services.jupyterLab.type }}
  selector:
  {{- include "spark-optimization.jupyterSelectorLabels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.jupyterLab.sparkUiPort2 }}
      targetPort: {{ .Values.services.jupyterLab.sparkUiTargetPort2 }}