version: '2.1'

volumes:
  shared-workspace:
    driver_opts:
      type: none
      device: ${SHARED_DIR}
      o: bind

services:
  jupyterlab:
    image: gcr.io/instruqt-godatadriven/jupyterlab:instruqt
    container_name: jupyterlab
    expose:
      - 4040
      - 4041
      - 8888
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - shared-workspace:/opt/workspace/shared
  spark-master:
    image: gcr.io/instruqt-godatadriven/spark-master:instruqt
    container_name: spark-master
    expose:
      - 7077
      - 8080
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace/shared
  spark-worker-1:
    image: gcr.io/instruqt-godatadriven/spark-worker:instruqt
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-1}
      - SPARK_WORKER_MEMORY=6g
      - SPARK_DAEMON_JAVA_OPTS='-DXms=5g'
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace/shared
    depends_on:
      - spark-master
  spark-worker-2:
    image: gcr.io/instruqt-godatadriven/spark-worker:instruqt
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-1}
      - SPARK_WORKER_MEMORY=6g
      - SPARK_DAEMON_JAVA_OPTS='-DXms=5g'
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace/shared
    depends_on:
      - spark-master
  spark-history:
    image: gcr.io/instruqt-godatadriven/spark-history:instruqt
    container_name: spark-history
    environment:
      - SPARK_HISTORY_OPTS='-Dspark.history.fs.logDirectory=/opt/workspace/history'
    ports:
      - 18080:18080
    volumes:
      - shared-workspace:/opt/workspace/shared
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:18080"]
        interval: 5s
        timeout: 2s
        retries: 5
  sparklint:
    image: roboxue/sparklint
    command: --historyServer http://spark-history:18080
    container_name: sparklint
    ports:
      - 23763:23763
    volumes:
      - shared-workspace:/opt/workspace/shared
    depends_on:
      spark-history:
        condition: service_healthy
