apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-optimization.name" . }}-worker-ui
  labels:
  {{- include "spark-optimization.commonLabels" . | indent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.services.sparkWorker.type }}
  selector:
  {{- include "spark-optimization.workerSelectorLabels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.sparkWorker.port }}
      targetPort: {{ .Values.services.sparkWorker.targetPort }}
